name: Job Variable Workflow

on: [push]

env:
  DOCKER_URL: some.docker.url

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{env.DOCKER_URL}}/image:latest
    steps:
      - name: Run a multi-line script
        run: |
          echo ${DOCKER_IMAGE}
